labelMappings:
- labels:
    - "ğŸ¤ B2B"
    globs:
      - "*B2B*"
- labels:
    - "ğŸ› ï¸ marketing tools"
    globs:
      - "*tools*"
- labels:
    - "ğŸš€ go to market / new product"
    globs:
      - "*Go*"
